// Core domain types for Aegis — mirrors backend/api/models.py Pydantic schemas

export type AgentId = 'detective' | 'diagnostician' | 'remediation' | 'reporter' | 'memory'

export type AgentStatus = 'active' | 'idle' | 'thinking' | 'error' | 'awaiting_approval'

export interface Agent {
  id: AgentId
  name: string
  role: string
  model: string
  status: AgentStatus
  metricLabel: string
  metricValue: number
  color: string
}

export type IncidentSeverity = 'critical' | 'warning' | 'info'

export type IncidentStatus =
  | 'detected'
  | 'diagnosing'
  | 'diagnosed'
  | 'awaiting_approval'
  | 'remediating'
  | 'resolved'
  | 'auto_resolved'
  | 'rejected'

export interface TimelineEvent {
  id: string
  agentId: AgentId
  timestamp: string // ISO 8601
  title: string
  detail: string
  status: 'complete' | 'in_progress' | 'pending'
}

export interface RemediationStep {
  id: string
  order: number
  description: string
  command?: string
  riskLevel: 'low' | 'medium' | 'high'
}

export interface Incident {
  id: string
  title: string
  service: string
  server: string
  severity: IncidentSeverity
  status: IncidentStatus
  detectedAt: string
  resolvedAt?: string
  rootCause?: string
  evidence: string[]
  remediationSteps: RemediationStep[]
  timeline: TimelineEvent[]
  isAutoResolved: boolean
  matchedMemoryId?: string
  metrics: {
    cpuBefore?: number
    cpuAfter?: number
    memoryBefore?: number
    memoryAfter?: number
    downtimeMinutes?: number
  }
}

export interface MemoryRecord {
  id: string
  incidentTitle: string
  rootCause: string
  fixApplied: string
  occurrences: number
  lastSeen: string
  confidenceScore: number
  autoApplyEligible: boolean
}

export interface IncidentReport {
  id: string
  incidentId: string
  title: string
  generatedAt: string
  summary: string
  rootCauseAnalysis: string
  actionsTaken: string[]
  downtimeMinutes: number
  costImpactEstimate?: string
  status: 'draft' | 'final'
  markdownReport?: string  // full Markdown document generated by Reporter Agent
}

export interface SystemHealth {
  allAgentsOperational: boolean
  lastIncidentAgo: string
  activeIncidentCount: number
  uptimePercentage: number
}

export interface ApprovalRequest {
  incidentId: string
  steps: RemediationStep[]
  requestedAt: string
  expiresInSeconds: number
}

export interface AdminServiceStatus {
  name: string
  status: string
  detail: string
}

export interface AdminOverview {
  environment: string
  apiPrefix: string
  authEnabled: boolean
  authMode: string
  backendStatus: string
  startupOk: boolean
  startupCheckedAt: string
  qwenConfigured: boolean
  databaseConfigured: boolean
  redisConfigured: boolean
  monitoredServers: string[]
  agentCount: number
  activeIncidentCount: number
  pendingApprovals: number
  reportCount: number
  memoryRecordCount: number
  docsUrl: string
  supportedScenarios: string[]
  serviceMatrix: AdminServiceStatus[]
  recentSignals: string[]
}
